/**
 * Workspace association maps behind the Session footer.
 *
 * The app's profile carries two flat JSON files, both regenerated by
 * `C:\Claude\bin\dsh_dashboard_links.py` from the dashboard contracts and the
 * Claude Design project list:
 *
 *   ~/.dsh/dashboard-links.json   workspace directory -> front-door URL
 *   ~/.dsh/design-links.json      workspace directory -> Claude Design project name
 *
 * A Session's workspace is immutable (it is the header cwd written at
 * creation), so resolving from it keeps the footer static for the life of the
 * Session with no extra state to store.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/** The dashboard and design project a Session workspace belongs to. */
export interface WorkspaceLinks {
  /** Front-door URL of the dashboard whose page source is this workspace. */
  readonly dashboardUrl?: string
  /** Name of the Claude Design project behind that dashboard. */
  readonly designProject?: string
}

const DASHBOARD_FILE = 'dashboard-links.json'
const DESIGN_FILE = 'design-links.json'
/**
 * Trailing segments every entry is also matched by: `packages/dashboards/src/<key>`.
 * That is what makes a Session inside a vercel-services worktree resolve, where
 * the absolute primary-checkout prefix of the mapped directory does not apply.
 */
const DASHBOARD_TAIL_SEGMENTS = 4

/**
 * Fold a path to the form the maps are compared in.
 * @param value - any absolute path, either separator.
 * @returns forward-slashed, trailing-slash-free, lowercased path.
 */
function normalizedPath(value: string): string {
  return value.replace(/[\\/]+/g, '/').replace(/\/+$/, '').toLowerCase()
}

/**
 * Read one map file into normalized path to value pairs.
 * @param path - absolute path of a flat `{ directory: string }` JSON file.
 * @returns the entries with non-empty string values; empty when unreadable.
 */
function readStringMap(path: string): ReadonlyMap<string, string> {
  try {
    const parsed: unknown = JSON.parse(readFileSync(path, 'utf8'))
    if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) return new Map()
    return new Map(Object.entries(parsed as Record<string, unknown>).filter(
      (entry): entry is [string, string] => typeof entry[1] === 'string' && entry[1] !== '',
    ))
  } catch {
    return new Map()
  }
}

/**
 * Load every workspace association under one profile directory.
 *
 * The two files are read independently on purpose: the design map can be
 * missing while the dashboard map is present, which is exactly the state a
 * build older than the design map leaves behind. A missing or malformed file
 * contributes nothing rather than failing the list, so an unreadable map costs
 * a blank footer line and never a broken sidebar.
 *
 * @param root - profile directory holding both map files.
 * @returns normalized workspace directory to merged association.
 */
export function loadWorkspaceLinks(root: string): ReadonlyMap<string, WorkspaceLinks> {
  const links = new Map<string, WorkspaceLinks>()
  const add = (directory: string, value: WorkspaceLinks): void => {
    const key = normalizedPath(directory)
    if (key === '') return
    links.set(key, { ...links.get(key), ...value })
  }
  for (const [directory, dashboardUrl] of readStringMap(join(root, DASHBOARD_FILE))) {
    add(directory, { dashboardUrl })
  }
  for (const [directory, designProject] of readStringMap(join(root, DESIGN_FILE))) {
    add(directory, { designProject })
  }
  return links
}

/**
 * Decide whether one Session workspace belongs to one mapped directory.
 * @param needle - normalized Session workspace path.
 * @param root - normalized mapped directory.
 * @returns true on the directory itself, a folder inside it, or its tail.
 */
function matches(needle: string, root: string): boolean {
  if (needle === root || needle.startsWith(`${root}/`)) return true
  const segments = root.split('/')
  if (segments.length < DASHBOARD_TAIL_SEGMENTS) return false
  const tail = segments.slice(-DASHBOARD_TAIL_SEGMENTS).join('/')
  return needle === tail || needle.endsWith(`/${tail}`) || needle.includes(`/${tail}/`)
}

/**
 * Resolve one Session workspace against the loaded maps.
 *
 * Two forms match, so the same dashboard is found from the primary checkout
 * and from any worktree of it: the mapped directory itself (or a folder inside
 * it), and the trailing `packages/dashboards/src/<key>` path. First match in
 * file order wins, which keeps the answer stable between runs.
 *
 * @param cwd - the Session's workspace directory, as its header records it.
 * @param links - map returned by {@link loadWorkspaceLinks}.
 * @returns the association, or an empty object when the workspace has none.
 */
export function resolveWorkspaceLinks(
  cwd: string | undefined,
  links: ReadonlyMap<string, WorkspaceLinks>,
): WorkspaceLinks {
  if (cwd === undefined || cwd === '') return {}
  const needle = normalizedPath(cwd)
  for (const [root, value] of links) {
    if (matches(needle, root)) return value
  }
  return {}
}
